### ISSUE TITLE
pitalium-explorerでブラウザ間比較でRunを実行するとエラーが発生する

### ISSUE THREAD

**Issue by tkmHashi** [hifive/hifive-pitalium#138]
```
java.lang.NullPointerException
	at com.htmlhifive.pitalium.image.util.SimilarityUtils.calcSimilarityPixelByPixel(SimilarityUtils.java:389)
	at com.htmlhifive.pitalium.image.util.SimilarityUtils.calcSimilarity(SimilarityUtils.java:80)
	at com.htmlhifive.pitalium.image.util.SimilarityUtils.calcSimilarity(SimilarityUtils.java:61)
	at com.htmlhifive.pitalium.image.util.ImagePair.calcEntireSimilarity(ImagePair.java:201)
	at com.htmlhifive.pitalium.image.util.ImagePair.compareImagePairAll(ImagePair.java:89)
	at com.htmlhifive.pitalium.explorer.io.ExplorerFilePersister.executeComparing(ExplorerFilePersister.java:227)
```

**Comment by ishikawa1027** [comment]
v1.2.1 で対応済み。
