### ISSUE TITLE
AndroidでHidden要素を指定してスクリーンショット取得時に例外が発生する。

### ISSUE THREAD

**Issue by meganetaaan** [hifive/hifive-pitalium#42]
### 現象

Android上のchromeに対してPitaliumのテストを実行時、
HiddenElementを指定して部分スクリーンショットを取得すると例外（RasterFormatException）が発生する。

### 環境

* Pitalium: v1.0.1
* Selenium grid/ node server： v2.48.2
* Appium: v1.4.14
* 対象OS： Android v4.4
* 対象ブラウザ： chrome

### 再現手順

下記テストを実行する。
```Java
public class PtlSampleTest extends PtlTestBase {

	private static final DomSelector[] HIDE_ELEMENTS = { new DomSelector(SelectorType.CLASS_NAME, "gototop") };

	@Test
	public void testCaptureTop() throws Exception {

		driver.get("http://www.htmlhifive.com");

		ScreenshotArgument arg = ScreenshotArgument.builder("トップページ")
		//
				.addNewTargetByTagName("body") // bodyをターゲットとして追加
				.addExcludeByClassName("fb-like-box") // bodyのうちfb-like-boxは除く
				//
				.addNewTargetById("about") // aboutをターゲットとして追加
				.addHiddenElementSelectors(HIDE_ELEMENTS) // スクリーンショット取得時にgototopを隠す
				.build();

		WebDriverWait wait = new WebDriverWait(driver, 30);
		wait.until(ExpectedConditions.presenceOfElementLocated(By
				.cssSelector("iframe[title=\"fb:like_box Facebook Social Plugin\"]")));

		assertionView.assertView(arg);
	}
}
```
なお".addHiddenElementSelectors(HIDE_ELEMENTS) "の行をコメントアウトすると例外は発生しなかった。

### スタックトレース

```
java.awt.image.RasterFormatException: y lies outside raster
	at sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:464)
	at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1203)
	at com.htmlhifive.pitalium.core.selenium.PtlWebDriver.cropScreenshotImage(PtlWebDriver.java:529)
	at com.htmlhifive.pitalium.core.selenium.PtlWebDriver.getScreenshotImage(PtlWebDriver.java:482)
	at com.htmlhifive.pitalium.core.selenium.PtlWebDriver.getTargetResult(PtlWebDriver.java:345)
	at com.htmlhifive.pitalium.core.selenium.SplitScreenshotWebDriver.getTargetResult(SplitScreenshotWebDriver.java:58)
	at com.htmlhifive.pitalium.core.selenium.PtlWebDriver.takeScreenshot(PtlWebDriver.java:327)
	at com.htmlhifive.pitalium.core.rules.AssertionView.takeCaptureAndPersistImage(AssertionView.java:437)
	at com.htmlhifive.pitalium.core.rules.AssertionView.assertView(AssertionView.java:328)
	at com.htmlhifive.pitalium.core.rules.AssertionView.assertView(AssertionView.java:287)
	at com.htmlhifive.pitalium.core.rules.AssertionView.assertView(AssertionView.java:275)
	at com.htmlhifive.pitalium.sample.PtlSampleTest.testCaptureTop(PtlSampleTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by tnakatan** [comment]
このエラーは、htmlhifive.comサイト内のカルーセルの高さが不統一であることが原因だった。   
カルーセルの5枚の画像のうち、モバイルで表示すると最初に表示されるSNSの画像のみ16px表示が下にずれてしまう。Xperia Z3の画面表示倍率は3なので、16x3=48となりエラーメッセージで表示されているピクセル数と一致する。  
Pitaliumはスクリーンショット撮影を始めるタイミング、及び移動後にウェブサイト全体及び対象要素の座標と大きさを測定する。上記テストでは常に移動前の測定が高さが大きい画像、移動後の測定が他の画像となっていた。そのため、テストに失敗していた。  

assertViewを実行する直前に以下のコードを実行してカルーセルを非表示とすると、エラーは発生しない。

```java
driver.executeJavaScript("document.getElementsByClassName('carousel')[0].style.display = 'none';");
```
